import traceback


def logError(e):
    print(traceback.format_exc())
